# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7908bdfef78d0fa74be41307aadd2a6c7e20101da4ddff23ff9eff2c0c5fa3cab5705a761d67aecd1b3129b33366deb57f3df6104949b694b6cff3a4e0e21851

test:
  secret_key_base: 638486171e4eb560220e18115d4ee643952b2a96f6fab7da674d9d20965611beb72cdc65d965d3693ec459f1749f846e7e9930db9e6b68875973c5b153402749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
